import prisma from "@/lib/db";

const passTypeData: Prisma.PassTypeCreateInput[] = [
  // Day pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    durationInDays: 1,
    price: 1.5,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    durationInDays: 1,
    price: 2.5,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    durationInDays: 1,
    price: 1.5,
  },
  // Monthly peak pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    isPeak: true,
    durationInDays: 31,
    price: 18.0,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    isPeak: true,
    durationInDays: 31,
    price: 30.0,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    isPeak: true,
    durationInDays: 31,
    price: 18.0,
  },
  // Monthly non-peak pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    isPeak: false,
    durationInDays: 31,
    price: 9.0,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    isPeak: false,
    durationInDays: 31,
    price: 15.0,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    isPeak: false,
    durationInDays: 31,
    price: 9.0,
  },
  // Half-yearly peak pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    isPeak: true,
    durationInDays: 183,
    price: 95.0,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    isPeak: true,
    durationInDays: 183,
    price: 160.0,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    isPeak: true,
    durationInDays: 183,
    price: 95.0,
  },
  // Half-yearly non-peak pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    isPeak: false,
    durationInDays: 183,
    price: 40.0,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    isPeak: false,
    durationInDays: 183,
    price: 40.0,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    isPeak: false,
    durationInDays: 183,
    price: 40.0,
  },
  // Yearly peak pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    isPeak: true,
    durationInDays: 365,
    price: 180.0,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    isPeak: true,
    durationInDays: 365,
    price: 300.0,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    isPeak: true,
    durationInDays: 365,
    price: 180.0,
  },
  // Yearly non-peak pass
  {
    type: "Gym",
    minAge: 12,
    maxAge: 17,
    isPeak: true,
    durationInDays: 365,
    price: 80.0,
  },
  {
    type: "Gym",
    minAge: 18,
    maxAge: 54,
    isPeak: true,
    durationInDays: 365,
    price: 80.0,
  },
  {
    type: "Gym",
    minAge: 55,
    maxAge: 65,
    isPeak: true,
    durationInDays: 365,
    price: 80.0,
  },
];
