import type { Metadata } from "next";
import { Providers } from "@/app/providers";
import { Container } from "@chakra-ui/react";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getSession } from "@/utils/getSession";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session?.user;
  return (
    <html lang="en">
      <body>
        <Providers>
          <Container maxW="1400px">
            <Navbar user={user} />
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
